### ISSUE TITLE
Need a clear  ReadMe and docs 

### ISSUE THREAD

**Issue by arvs47** [sheetbase/sheets#15]
Hello I found your sheetbase project an interesting one and have a good growth in future , but i am struggling here as with the readme and docs . please provide some clarification on these ,
I know these are dumbest question but i need some clarity 
What is this source code about ,is this about sheetbase.dev site or the entire code that can function as sheetcode projects . Does your site provide the users to make website as a service .
 what are the requirements  do i need a node server or just app script and git hub page is fine .
How can i use your site to make my own website using db as sheet 
what is this google app script library for 

A video would be fine to identify the possibilities of your project , 
I am not a development guy but do some reverse  and make some script in GAS . you can find my works in git and trying to utilize your project possibilities 
thanks .

**Comment by lamnhan** [comment]
Hello,
Thank you for your comment!
This repo is only a part of the Sheetbase platform.
Please see the docs: <https://sheetbase.dev/docs> for more information.
We try our best to make the platform better, along the way, there may be missing information in the Docs.
For any problem, please let us know, so we can support you better.
Thank you!

**Comment by arvs47** [comment]
> Hello,
> Thank you for your comment!
> This repo is only a part of the Sheetbase platform.
> Please see the docs: https://sheetbase.dev/docs for more information.
> We try our best to make the platform better, along the way, there may be missing information in the Docs.
> For any problem, please let us know, so we can support you better.
> Thank you!

Hello Thank you for the reply . So when are you going to start the service in sheetbase platform For the end users .and remember to add a redirect to your old url to new url if it not available Kindly update in relevant platforms like medium
